In [12]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from sklearn.cross_validation import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.linear_model import LinearRegression

Get the dataset

In [2]:
dataset = pd.read_csv('../../datasets/regression/Multiple_Linear_Regression/50_Startups.csv')
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

Determine the features (X) and dependent factor (Y).

X is of course column 1 to 4, and Y is column 5

In [6]:
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, 4].values

Encode categorical data (column 4) using label encoder

In [10]:
labelEncoder_X = LabelEncoder()
X[:, 3] = labelEncoder_X.fit_transform(X[:,3])

oneHotEncoder = OneHotEncoder(categorical_features=[3])
X = oneHotEncoder.fit_transform(X).toarray()

X

array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          1.00000000e+00,   1.36897800e+05,   4.71784100e+05],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   1.51377590e+05,   4.43898530e+05],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   1.01145550e+05,   4.07934540e+05],
       ..., 
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   1.35426920e+05,   0.00000000e+00],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          1.00000000e+00,   5.17431500e+04,   0.00000000e+00],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   1.16983800e+05,   4.51730600e+04]])

Split the dataset into training set and test set

In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

Fit multiple linear regression to the training set

In [16]:
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

Predict the test set results

In [17]:
Y_prediction = regressor.predict(X_test)

finally, compare the predicted profit (Y_prediction) and the real profit (Y_test). For now, we can only do it manually 

In [18]:
Y_prediction

array([ 198994.31173386,   59244.67076855,   85489.14518471,
         37377.01565046,   82126.79215262,  136233.13423812,
         20217.98294408,  159453.94706001,  111211.37370373,
         62776.32559406])

In [19]:
Y_test

array([ 103282.38,  144259.4 ,  146121.95,   77798.83,  191050.39,
        105008.31,   81229.06,   97483.56,  110352.25,  166187.94])

## Building the Optimal Model using Backward Elimination

What if, among those features, there are those that highly significant to the dependent variable, and some that is least significant? Can we remove those insignificant feature?

So first, we need to evaluate the significance of the features. We are going to use `statsmodels` library

In [21]:
import statsmodels.formula.api as sm

Add column b0 (the constant part of the multiple linear regression equation), as it is required by the `statsmodels` 

In [23]:
# we use np built-in method 'ones' to create column of 1s with 50 rows
# axis=1 means we add to the column
X = np.append(arr=np.ones((50,1)).astype(int), values=X,axis=1)  
X

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          1.00000000e+00,   1.36897800e+05,   4.71784100e+05],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   1.51377590e+05,   4.43898530e+05],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   1.01145550e+05,   4.07934540e+05],
       ..., 
       [  1.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   1.35426920e+05,   0.00000000e+00],
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00, ...,
          1.00000000e+00,   5.17431500e+04,   0.00000000e+00],
       [  1.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   1.16983800e+05,   4.51730600e+04]])

_Step 1_ Select a significance level to stay in the model (e.g. SL = 0.05)

`X_opt` is the optimal matrix of features (only statistically significant for the dependent variable)

In [25]:
# specify all the indices of the column containing features
X_opt = X[:, [0,1,2,3,4,5]]

_Step 2_ - Fit the model with all possible predictors

Fit the full model with all possible predictors to the future optimal matrix features (`X_opt`).

Create new regressor, which is a new object from ordinary least square from `statsmodel`

In [27]:
regressor_OLS = sm.OLS(endog=Y, exog=X_opt).fit()  # ordinary least square

_Step 3_ Consider the predictor with the highest P value. if P value > significant level, go to the next step. otherwise, finish

In [28]:
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.392
Model:                            OLS   Adj. R-squared:                  0.323
Method:                 Least Squares   F-statistic:                     5.670
Date:                Sun, 16 Apr 2017   Prob (F-statistic):           0.000405
Time:                        07:29:17   Log-Likelihood:                -588.22
No. Observations:                  50   AIC:                             1188.
Df Residuals:                      44   BIC:                             1200.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        1.21e+05   5000.589     24.195      0.000    1.11e+05    1.31e+05
x1         -9.237e+04    2.4e+04     -3.852      0.000   -1.41e+05    -4.4e+04
x2         -8.532e+04   3.35e+04     -2.543      0.015   -1.53e+05   -1.77e+04
x3         -5.606e+04   3.35e+04     -1.671      0.102   -1.24e+05    1.15e+04
x4          -7.15e+04   3.35e+04     -2.131      0.039   -1.39e+05   -3893.387
x5         -5.123e+04   3.35e+04     -1.527      0.134   -1.19e+05    1.64e+04
==============================================================================
Omnibus:                        3.161   Durbin-Watson:                   0.208
Prob(Omnibus):                  0.206   Jarque-Bera (JB):                2.855
Skew:                           0.579   Prob(JB):                        0.240
Kurtosis:                       2.835   Cond. No.                         7.42
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

Take note to the P-values `P>[t]` from the result above:

__"The lower the P-value, the more significant the feature is going to be to the dependent variable"__

It means that we need to remove feature with the highest P value (x5)

_Step 4_- remove feature with insignificant influence

_Step 5_ - Fit model without this variable

In [29]:
X_opt = X[:, [0,1,2,3,4]]
regressor_OLS = sm.OLS(endog=Y, exog=X_opt).fit() 
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.360
Model:                            OLS   Adj. R-squared:                  0.303
Method:                 Least Squares   F-statistic:                     6.318
Date:                Sun, 16 Apr 2017   Prob (F-statistic):           0.000401
Time:                        07:38:24   Log-Likelihood:                -589.51
No. Observations:                  50   AIC:                             1189.
Df Residuals:                      45   BIC:                             1199.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.199e+05   5017.385     23.887      0.000     1.1e+05     1.3e+05
x1         -9.123e+04   2.43e+04     -3.751      0.001    -1.4e+05   -4.22e+04
x2         -8.418e+04    3.4e+04     -2.474      0.017   -1.53e+05   -1.56e+04
x3         -5.493e+04    3.4e+04     -1.614      0.114   -1.23e+05    1.36e+04
x4         -7.036e+04    3.4e+04     -2.068      0.044   -1.39e+05   -1821.325
==============================================================================
Omnibus:                        2.953   Durbin-Watson:                   0.086
Prob(Omnibus):                  0.228   Jarque-Bera (JB):                2.730
Skew:                           0.560   Prob(JB):                        0.255
Kurtosis:                       2.761   Cond. No.                         7.33
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""